"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DeviceInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    HARDWARE_VERSION_FIELD_NUMBER: builtins.int
    SOFTWARE_VERSION_FIELD_NUMBER: builtins.int
    COUNTRY_CODE_FIELD_NUMBER: builtins.int
    UTC_OFFSET_S_FIELD_NUMBER: builtins.int
    id: builtins.str
    hardware_version: builtins.str
    software_version: builtins.str
    country_code: builtins.str
    utc_offset_s: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str | None = ...,
        hardware_version: builtins.str | None = ...,
        software_version: builtins.str | None = ...,
        country_code: builtins.str | None = ...,
        utc_offset_s: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_country_code", b"_country_code", "_hardware_version", b"_hardware_version", "_id", b"_id", "_software_version", b"_software_version", "_utc_offset_s", b"_utc_offset_s", "country_code", b"country_code", "hardware_version", b"hardware_version", "id", b"id", "software_version", b"software_version", "utc_offset_s", b"utc_offset_s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_country_code", b"_country_code", "_hardware_version", b"_hardware_version", "_id", b"_id", "_software_version", b"_software_version", "_utc_offset_s", b"_utc_offset_s", "country_code", b"country_code", "hardware_version", b"hardware_version", "id", b"id", "software_version", b"software_version", "utc_offset_s", b"utc_offset_s"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_country_code", b"_country_code"]) -> typing.Literal["country_code"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_hardware_version", b"_hardware_version"]) -> typing.Literal["hardware_version"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_software_version", b"_software_version"]) -> typing.Literal["software_version"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_utc_offset_s", b"_utc_offset_s"]) -> typing.Literal["utc_offset_s"] | None: ...

global___DeviceInfo = DeviceInfo

@typing.final
class DeviceState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPTIME_S_FIELD_NUMBER: builtins.int
    uptime_s: builtins.int
    def __init__(
        self,
        *,
        uptime_s: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_uptime_s", b"_uptime_s", "uptime_s", b"uptime_s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_uptime_s", b"_uptime_s", "uptime_s", b"uptime_s"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_uptime_s", b"_uptime_s"]) -> typing.Literal["uptime_s"] | None: ...

global___DeviceState = DeviceState

@typing.final
class SignedData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    signature: builtins.bytes
    def __init__(
        self,
        *,
        data: builtins.bytes | None = ...,
        signature: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_data", b"_data", "_signature", b"_signature", "data", b"data", "signature", b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_data", b"_data", "_signature", b"_signature", "data", b"data", "signature", b"signature"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_data", b"_data"]) -> typing.Literal["data"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_signature", b"_signature"]) -> typing.Literal["signature"] | None: ...

global___SignedData = SignedData

@typing.final
class GetNextIdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetNextIdRequest = GetNextIdRequest

@typing.final
class GetNextIdResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EPOCH_ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    epoch_id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        epoch_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_epoch_id", b"_epoch_id", "_id", b"_id", "epoch_id", b"epoch_id", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_epoch_id", b"_epoch_id", "_id", b"_id", "epoch_id", b"epoch_id", "id", b"id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_epoch_id", b"_epoch_id"]) -> typing.Literal["epoch_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...

global___GetNextIdResponse = GetNextIdResponse

@typing.final
class PingTarget(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    service: builtins.str
    location: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        service: builtins.str | None = ...,
        location: builtins.str | None = ...,
        address: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_address", b"_address", "_location", b"_location", "_service", b"_service", "address", b"address", "location", b"location", "service", b"service"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_address", b"_address", "_location", b"_location", "_service", b"_service", "address", b"address", "location", b"location", "service", b"service"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_address", b"_address"]) -> typing.Literal["address"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_location", b"_location"]) -> typing.Literal["location"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_service", b"_service"]) -> typing.Literal["service"] | None: ...

global___PingTarget = PingTarget

@typing.final
class PingResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_FIELD_NUMBER: builtins.int
    DROPRATE_FIELD_NUMBER: builtins.int
    LATENCYMS_FIELD_NUMBER: builtins.int
    dropRate: builtins.float
    latencyMs: builtins.float
    @property
    def target(self) -> global___PingTarget: ...
    def __init__(
        self,
        *,
        target: global___PingTarget | None = ...,
        dropRate: builtins.float | None = ...,
        latencyMs: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dropRate", b"_dropRate", "_latencyMs", b"_latencyMs", "_target", b"_target", "dropRate", b"dropRate", "latencyMs", b"latencyMs", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dropRate", b"_dropRate", "_latencyMs", b"_latencyMs", "_target", b"_target", "dropRate", b"dropRate", "latencyMs", b"latencyMs", "target", b"target"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dropRate", b"_dropRate"]) -> typing.Literal["dropRate"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latencyMs", b"_latencyMs"]) -> typing.Literal["latencyMs"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_target", b"_target"]) -> typing.Literal["target"] | None: ...

global___PingResult = PingResult

@typing.final
class BondingChallenge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISH_ID_FIELD_NUMBER: builtins.int
    WIFI_ID_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    dish_id: builtins.str
    wifi_id: builtins.str
    nonce: builtins.bytes
    def __init__(
        self,
        *,
        dish_id: builtins.str | None = ...,
        wifi_id: builtins.str | None = ...,
        nonce: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dish_id", b"_dish_id", "_nonce", b"_nonce", "_wifi_id", b"_wifi_id", "dish_id", b"dish_id", "nonce", b"nonce", "wifi_id", b"wifi_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dish_id", b"_dish_id", "_nonce", b"_nonce", "_wifi_id", b"_wifi_id", "dish_id", b"dish_id", "nonce", b"nonce", "wifi_id", b"wifi_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dish_id", b"_dish_id"]) -> typing.Literal["dish_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_nonce", b"_nonce"]) -> typing.Literal["nonce"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_wifi_id", b"_wifi_id"]) -> typing.Literal["wifi_id"] | None: ...

global___BondingChallenge = BondingChallenge

@typing.final
class AuthenticateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHALLENGE_FIELD_NUMBER: builtins.int
    @property
    def challenge(self) -> global___SignedData: ...
    def __init__(
        self,
        *,
        challenge: global___SignedData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_challenge", b"_challenge", "challenge", b"challenge"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_challenge", b"_challenge", "challenge", b"challenge"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_challenge", b"_challenge"]) -> typing.Literal["challenge"] | None: ...

global___AuthenticateRequest = AuthenticateRequest

@typing.final
class ChallengeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIGNATURE_FIELD_NUMBER: builtins.int
    CERTIFICATE_CHAIN_FIELD_NUMBER: builtins.int
    signature: builtins.bytes
    certificate_chain: builtins.bytes
    def __init__(
        self,
        *,
        signature: builtins.bytes | None = ...,
        certificate_chain: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_certificate_chain", b"_certificate_chain", "_signature", b"_signature", "certificate_chain", b"certificate_chain", "signature", b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_certificate_chain", b"_certificate_chain", "_signature", b"_signature", "certificate_chain", b"certificate_chain", "signature", b"signature"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_certificate_chain", b"_certificate_chain"]) -> typing.Literal["certificate_chain"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_signature", b"_signature"]) -> typing.Literal["signature"] | None: ...

global___ChallengeResponse = ChallengeResponse

@typing.final
class NetworkInterface(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class RxStats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BYTES_FIELD_NUMBER: builtins.int
        PACKETS_FIELD_NUMBER: builtins.int
        FRAME_ERRORS_FIELD_NUMBER: builtins.int
        bytes: builtins.int
        packets: builtins.int
        frame_errors: builtins.int
        def __init__(
            self,
            *,
            bytes: builtins.int | None = ...,
            packets: builtins.int | None = ...,
            frame_errors: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_bytes", b"_bytes", "_frame_errors", b"_frame_errors", "_packets", b"_packets", "bytes", b"bytes", "frame_errors", b"frame_errors", "packets", b"packets"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_bytes", b"_bytes", "_frame_errors", b"_frame_errors", "_packets", b"_packets", "bytes", b"bytes", "frame_errors", b"frame_errors", "packets", b"packets"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_bytes", b"_bytes"]) -> typing.Literal["bytes"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_frame_errors", b"_frame_errors"]) -> typing.Literal["frame_errors"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_packets", b"_packets"]) -> typing.Literal["packets"] | None: ...

    @typing.final
    class TxStats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BYTES_FIELD_NUMBER: builtins.int
        PACKETS_FIELD_NUMBER: builtins.int
        bytes: builtins.int
        packets: builtins.int
        def __init__(
            self,
            *,
            bytes: builtins.int | None = ...,
            packets: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_bytes", b"_bytes", "_packets", b"_packets", "bytes", b"bytes", "packets", b"packets"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_bytes", b"_bytes", "_packets", b"_packets", "bytes", b"bytes", "packets", b"packets"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_bytes", b"_bytes"]) -> typing.Literal["bytes"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_packets", b"_packets"]) -> typing.Literal["packets"] | None: ...

    NAME_FIELD_NUMBER: builtins.int
    RX_STATS_FIELD_NUMBER: builtins.int
    TX_STATS_FIELD_NUMBER: builtins.int
    ETHERNET_FIELD_NUMBER: builtins.int
    WIFI_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def rx_stats(self) -> global___NetworkInterface.RxStats: ...
    @property
    def tx_stats(self) -> global___NetworkInterface.TxStats: ...
    @property
    def ethernet(self) -> global___EthernetNetworkInterface: ...
    @property
    def wifi(self) -> global___WifiNetworkInterface: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        rx_stats: global___NetworkInterface.RxStats | None = ...,
        tx_stats: global___NetworkInterface.TxStats | None = ...,
        ethernet: global___EthernetNetworkInterface | None = ...,
        wifi: global___WifiNetworkInterface | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_name", b"_name", "_rx_stats", b"_rx_stats", "_tx_stats", b"_tx_stats", "ethernet", b"ethernet", "interface", b"interface", "name", b"name", "rx_stats", b"rx_stats", "tx_stats", b"tx_stats", "wifi", b"wifi"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_name", b"_name", "_rx_stats", b"_rx_stats", "_tx_stats", b"_tx_stats", "ethernet", b"ethernet", "interface", b"interface", "name", b"name", "rx_stats", b"rx_stats", "tx_stats", b"tx_stats", "wifi", b"wifi"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rx_stats", b"_rx_stats"]) -> typing.Literal["rx_stats"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tx_stats", b"_tx_stats"]) -> typing.Literal["tx_stats"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["interface", b"interface"]) -> typing.Literal["ethernet", "wifi"] | None: ...

global___NetworkInterface = NetworkInterface

@typing.final
class EthernetNetworkInterface(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Duplex:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DuplexEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EthernetNetworkInterface._Duplex.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: EthernetNetworkInterface._Duplex.ValueType  # 0
        HALF: EthernetNetworkInterface._Duplex.ValueType  # 1
        FULL: EthernetNetworkInterface._Duplex.ValueType  # 2

    class Duplex(_Duplex, metaclass=_DuplexEnumTypeWrapper): ...
    UNKNOWN: EthernetNetworkInterface.Duplex.ValueType  # 0
    HALF: EthernetNetworkInterface.Duplex.ValueType  # 1
    FULL: EthernetNetworkInterface.Duplex.ValueType  # 2

    LINK_DETECTED_FIELD_NUMBER: builtins.int
    SPEED_MBPS_FIELD_NUMBER: builtins.int
    AUTONEGOTIATION_ON_FIELD_NUMBER: builtins.int
    DUPLEX_FIELD_NUMBER: builtins.int
    link_detected: builtins.bool
    speed_mbps: builtins.int
    autonegotiation_on: builtins.bool
    duplex: global___EthernetNetworkInterface.Duplex.ValueType
    def __init__(
        self,
        *,
        link_detected: builtins.bool | None = ...,
        speed_mbps: builtins.int | None = ...,
        autonegotiation_on: builtins.bool | None = ...,
        duplex: global___EthernetNetworkInterface.Duplex.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_autonegotiation_on", b"_autonegotiation_on", "_duplex", b"_duplex", "_link_detected", b"_link_detected", "_speed_mbps", b"_speed_mbps", "autonegotiation_on", b"autonegotiation_on", "duplex", b"duplex", "link_detected", b"link_detected", "speed_mbps", b"speed_mbps"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_autonegotiation_on", b"_autonegotiation_on", "_duplex", b"_duplex", "_link_detected", b"_link_detected", "_speed_mbps", b"_speed_mbps", "autonegotiation_on", b"autonegotiation_on", "duplex", b"duplex", "link_detected", b"link_detected", "speed_mbps", b"speed_mbps"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_autonegotiation_on", b"_autonegotiation_on"]) -> typing.Literal["autonegotiation_on"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_duplex", b"_duplex"]) -> typing.Literal["duplex"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_link_detected", b"_link_detected"]) -> typing.Literal["link_detected"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_speed_mbps", b"_speed_mbps"]) -> typing.Literal["speed_mbps"] | None: ...

global___EthernetNetworkInterface = EthernetNetworkInterface

@typing.final
class WifiNetworkInterface(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ThermalStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LEVEL_FIELD_NUMBER: builtins.int
        TEMP_FIELD_NUMBER: builtins.int
        level: builtins.int
        temp: builtins.int
        def __init__(
            self,
            *,
            level: builtins.int | None = ...,
            temp: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_level", b"_level", "_temp", b"_temp", "level", b"level", "temp", b"temp"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_level", b"_level", "_temp", b"_temp", "level", b"level", "temp", b"temp"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_level", b"_level"]) -> typing.Literal["level"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_temp", b"_temp"]) -> typing.Literal["temp"] | None: ...

    THERMAL_STATUS_FIELD_NUMBER: builtins.int
    @property
    def thermal_status(self) -> global___WifiNetworkInterface.ThermalStatus: ...
    def __init__(
        self,
        *,
        thermal_status: global___WifiNetworkInterface.ThermalStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_thermal_status", b"_thermal_status", "thermal_status", b"thermal_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_thermal_status", b"_thermal_status", "thermal_status", b"thermal_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_thermal_status", b"_thermal_status"]) -> typing.Literal["thermal_status"] | None: ...

global___WifiNetworkInterface = WifiNetworkInterface

@typing.final
class LLAPosition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAT_FIELD_NUMBER: builtins.int
    LON_FIELD_NUMBER: builtins.int
    ALT_FIELD_NUMBER: builtins.int
    lat: builtins.float
    lon: builtins.float
    alt: builtins.float
    def __init__(
        self,
        *,
        lat: builtins.float | None = ...,
        lon: builtins.float | None = ...,
        alt: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_alt", b"_alt", "_lat", b"_lat", "_lon", b"_lon", "alt", b"alt", "lat", b"lat", "lon", b"lon"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_alt", b"_alt", "_lat", b"_lat", "_lon", b"_lon", "alt", b"alt", "lat", b"lat", "lon", b"lon"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_alt", b"_alt"]) -> typing.Literal["alt"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_lat", b"_lat"]) -> typing.Literal["lat"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_lon", b"_lon"]) -> typing.Literal["lon"] | None: ...

global___LLAPosition = LLAPosition

@typing.final
class ECEFPosition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float | None = ...,
        y: builtins.float | None = ...,
        z: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_x", b"_x", "_y", b"_y", "_z", b"_z", "x", b"x", "y", b"y", "z", b"z"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_x", b"_x", "_y", b"_y", "_z", b"_z", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_x", b"_x"]) -> typing.Literal["x"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_y", b"_y"]) -> typing.Literal["y"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_z", b"_z"]) -> typing.Literal["z"] | None: ...

global___ECEFPosition = ECEFPosition
