"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Capability:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CapabilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Capability.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    READ: _Capability.ValueType  # 0
    WRITE: _Capability.ValueType  # 1
    DEBUG: _Capability.ValueType  # 2
    ADMIN: _Capability.ValueType  # 3
    SETUP: _Capability.ValueType  # 4
    SET_SKU: _Capability.ValueType  # 5
    REFRESH: _Capability.ValueType  # 6
    READ_PRIVATE: _Capability.ValueType  # 7

class Capability(_Capability, metaclass=_CapabilityEnumTypeWrapper): ...

READ: Capability.ValueType  # 0
WRITE: Capability.ValueType  # 1
DEBUG: Capability.ValueType  # 2
ADMIN: Capability.ValueType  # 3
SETUP: Capability.ValueType  # 4
SET_SKU: Capability.ValueType  # 5
REFRESH: Capability.ValueType  # 6
READ_PRIVATE: Capability.ValueType  # 7
global___Capability = Capability

@typing.final
class PublicKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    CAPABILITIES_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def capabilities(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Capability.ValueType]: ...
    def __init__(
        self,
        *,
        key: builtins.str | None = ...,
        capabilities: collections.abc.Iterable[global___Capability.ValueType] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_key", b"_key", "key", b"key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_key", b"_key", "capabilities", b"capabilities", "key", b"key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_key", b"_key"]) -> typing.Literal["key"] | None: ...

global___PublicKey = PublicKey
