"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import spacex.api.device.common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DishState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DishStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DishState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _DishState.ValueType  # 0
    CONNECTED: _DishState.ValueType  # 1
    SEARCHING: _DishState.ValueType  # 2
    BOOTING: _DishState.ValueType  # 3

class DishState(_DishState, metaclass=_DishStateEnumTypeWrapper): ...

UNKNOWN: DishState.ValueType  # 0
CONNECTED: DishState.ValueType  # 1
SEARCHING: DishState.ValueType  # 2
BOOTING: DishState.ValueType  # 3
global___DishState = DishState

@typing.final
class DishStowRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNSTOW_FIELD_NUMBER: builtins.int
    unstow: builtins.bool
    def __init__(
        self,
        *,
        unstow: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_unstow", b"_unstow", "unstow", b"unstow"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_unstow", b"_unstow", "unstow", b"unstow"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_unstow", b"_unstow"]) -> typing.Literal["unstow"] | None: ...

global___DishStowRequest = DishStowRequest

@typing.final
class DishStowResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DishStowResponse = DishStowResponse

@typing.final
class DishGetContextRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DishGetContextRequest = DishGetContextRequest

@typing.final
class DishGetContextResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEVICE_INFO_FIELD_NUMBER: builtins.int
    DEVICE_STATE_FIELD_NUMBER: builtins.int
    OBSTRUCTION_FRACTION_FIELD_NUMBER: builtins.int
    OBSTRUCTION_VALID_S_FIELD_NUMBER: builtins.int
    CELL_ID_FIELD_NUMBER: builtins.int
    POP_RACK_ID_FIELD_NUMBER: builtins.int
    INITIAL_SATELLITE_ID_FIELD_NUMBER: builtins.int
    INITIAL_GATEWAY_ID_FIELD_NUMBER: builtins.int
    ON_BACKUP_BEAM_FIELD_NUMBER: builtins.int
    SECONDS_TO_SLOT_END_FIELD_NUMBER: builtins.int
    obstruction_fraction: builtins.float
    obstruction_valid_s: builtins.float
    cell_id: builtins.int
    pop_rack_id: builtins.int
    initial_satellite_id: builtins.int
    initial_gateway_id: builtins.int
    on_backup_beam: builtins.bool
    seconds_to_slot_end: builtins.float
    @property
    def device_info(self) -> spacex.api.device.common_pb2.DeviceInfo: ...
    @property
    def device_state(self) -> spacex.api.device.common_pb2.DeviceState: ...
    def __init__(
        self,
        *,
        device_info: spacex.api.device.common_pb2.DeviceInfo | None = ...,
        device_state: spacex.api.device.common_pb2.DeviceState | None = ...,
        obstruction_fraction: builtins.float | None = ...,
        obstruction_valid_s: builtins.float | None = ...,
        cell_id: builtins.int | None = ...,
        pop_rack_id: builtins.int | None = ...,
        initial_satellite_id: builtins.int | None = ...,
        initial_gateway_id: builtins.int | None = ...,
        on_backup_beam: builtins.bool | None = ...,
        seconds_to_slot_end: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_cell_id", b"_cell_id", "_device_info", b"_device_info", "_device_state", b"_device_state", "_initial_gateway_id", b"_initial_gateway_id", "_initial_satellite_id", b"_initial_satellite_id", "_obstruction_fraction", b"_obstruction_fraction", "_obstruction_valid_s", b"_obstruction_valid_s", "_on_backup_beam", b"_on_backup_beam", "_pop_rack_id", b"_pop_rack_id", "_seconds_to_slot_end", b"_seconds_to_slot_end", "cell_id", b"cell_id", "device_info", b"device_info", "device_state", b"device_state", "initial_gateway_id", b"initial_gateway_id", "initial_satellite_id", b"initial_satellite_id", "obstruction_fraction", b"obstruction_fraction", "obstruction_valid_s", b"obstruction_valid_s", "on_backup_beam", b"on_backup_beam", "pop_rack_id", b"pop_rack_id", "seconds_to_slot_end", b"seconds_to_slot_end"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_cell_id", b"_cell_id", "_device_info", b"_device_info", "_device_state", b"_device_state", "_initial_gateway_id", b"_initial_gateway_id", "_initial_satellite_id", b"_initial_satellite_id", "_obstruction_fraction", b"_obstruction_fraction", "_obstruction_valid_s", b"_obstruction_valid_s", "_on_backup_beam", b"_on_backup_beam", "_pop_rack_id", b"_pop_rack_id", "_seconds_to_slot_end", b"_seconds_to_slot_end", "cell_id", b"cell_id", "device_info", b"device_info", "device_state", b"device_state", "initial_gateway_id", b"initial_gateway_id", "initial_satellite_id", b"initial_satellite_id", "obstruction_fraction", b"obstruction_fraction", "obstruction_valid_s", b"obstruction_valid_s", "on_backup_beam", b"on_backup_beam", "pop_rack_id", b"pop_rack_id", "seconds_to_slot_end", b"seconds_to_slot_end"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_cell_id", b"_cell_id"]) -> typing.Literal["cell_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_device_info", b"_device_info"]) -> typing.Literal["device_info"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_device_state", b"_device_state"]) -> typing.Literal["device_state"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_initial_gateway_id", b"_initial_gateway_id"]) -> typing.Literal["initial_gateway_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_initial_satellite_id", b"_initial_satellite_id"]) -> typing.Literal["initial_satellite_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_obstruction_fraction", b"_obstruction_fraction"]) -> typing.Literal["obstruction_fraction"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_obstruction_valid_s", b"_obstruction_valid_s"]) -> typing.Literal["obstruction_valid_s"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_on_backup_beam", b"_on_backup_beam"]) -> typing.Literal["on_backup_beam"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pop_rack_id", b"_pop_rack_id"]) -> typing.Literal["pop_rack_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_to_slot_end", b"_seconds_to_slot_end"]) -> typing.Literal["seconds_to_slot_end"] | None: ...

global___DishGetContextResponse = DishGetContextResponse

@typing.final
class DishGetHistoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENT_FIELD_NUMBER: builtins.int
    POP_PING_DROP_RATE_FIELD_NUMBER: builtins.int
    POP_PING_LATENCY_MS_FIELD_NUMBER: builtins.int
    DOWNLINK_THROUGHPUT_BPS_FIELD_NUMBER: builtins.int
    UPLINK_THROUGHPUT_BPS_FIELD_NUMBER: builtins.int
    SNR_FIELD_NUMBER: builtins.int
    SCHEDULED_FIELD_NUMBER: builtins.int
    OBSTRUCTED_FIELD_NUMBER: builtins.int
    current: builtins.int
    @property
    def pop_ping_drop_rate(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def pop_ping_latency_ms(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def downlink_throughput_bps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def uplink_throughput_bps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def snr(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def scheduled(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    @property
    def obstructed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    def __init__(
        self,
        *,
        current: builtins.int | None = ...,
        pop_ping_drop_rate: collections.abc.Iterable[builtins.float] | None = ...,
        pop_ping_latency_ms: collections.abc.Iterable[builtins.float] | None = ...,
        downlink_throughput_bps: collections.abc.Iterable[builtins.float] | None = ...,
        uplink_throughput_bps: collections.abc.Iterable[builtins.float] | None = ...,
        snr: collections.abc.Iterable[builtins.float] | None = ...,
        scheduled: collections.abc.Iterable[builtins.bool] | None = ...,
        obstructed: collections.abc.Iterable[builtins.bool] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_current", b"_current", "current", b"current"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_current", b"_current", "current", b"current", "downlink_throughput_bps", b"downlink_throughput_bps", "obstructed", b"obstructed", "pop_ping_drop_rate", b"pop_ping_drop_rate", "pop_ping_latency_ms", b"pop_ping_latency_ms", "scheduled", b"scheduled", "snr", b"snr", "uplink_throughput_bps", b"uplink_throughput_bps"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_current", b"_current"]) -> typing.Literal["current"] | None: ...

global___DishGetHistoryResponse = DishGetHistoryResponse

@typing.final
class DishGetStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEVICE_INFO_FIELD_NUMBER: builtins.int
    DEVICE_STATE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    ALERTS_FIELD_NUMBER: builtins.int
    SNR_FIELD_NUMBER: builtins.int
    SECONDS_TO_FIRST_NONEMPTY_SLOT_FIELD_NUMBER: builtins.int
    POP_PING_DROP_RATE_FIELD_NUMBER: builtins.int
    DOWNLINK_THROUGHPUT_BPS_FIELD_NUMBER: builtins.int
    UPLINK_THROUGHPUT_BPS_FIELD_NUMBER: builtins.int
    POP_PING_LATENCY_MS_FIELD_NUMBER: builtins.int
    OBSTRUCTION_STATS_FIELD_NUMBER: builtins.int
    STOW_REQUESTED_FIELD_NUMBER: builtins.int
    state: global___DishState.ValueType
    snr: builtins.float
    seconds_to_first_nonempty_slot: builtins.float
    pop_ping_drop_rate: builtins.float
    downlink_throughput_bps: builtins.float
    uplink_throughput_bps: builtins.float
    pop_ping_latency_ms: builtins.float
    stow_requested: builtins.bool
    @property
    def device_info(self) -> spacex.api.device.common_pb2.DeviceInfo: ...
    @property
    def device_state(self) -> spacex.api.device.common_pb2.DeviceState: ...
    @property
    def alerts(self) -> global___DishAlerts: ...
    @property
    def obstruction_stats(self) -> global___DishObstructionStats: ...
    def __init__(
        self,
        *,
        device_info: spacex.api.device.common_pb2.DeviceInfo | None = ...,
        device_state: spacex.api.device.common_pb2.DeviceState | None = ...,
        state: global___DishState.ValueType | None = ...,
        alerts: global___DishAlerts | None = ...,
        snr: builtins.float | None = ...,
        seconds_to_first_nonempty_slot: builtins.float | None = ...,
        pop_ping_drop_rate: builtins.float | None = ...,
        downlink_throughput_bps: builtins.float | None = ...,
        uplink_throughput_bps: builtins.float | None = ...,
        pop_ping_latency_ms: builtins.float | None = ...,
        obstruction_stats: global___DishObstructionStats | None = ...,
        stow_requested: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_alerts", b"_alerts", "_device_info", b"_device_info", "_device_state", b"_device_state", "_downlink_throughput_bps", b"_downlink_throughput_bps", "_obstruction_stats", b"_obstruction_stats", "_pop_ping_drop_rate", b"_pop_ping_drop_rate", "_pop_ping_latency_ms", b"_pop_ping_latency_ms", "_seconds_to_first_nonempty_slot", b"_seconds_to_first_nonempty_slot", "_snr", b"_snr", "_state", b"_state", "_stow_requested", b"_stow_requested", "_uplink_throughput_bps", b"_uplink_throughput_bps", "alerts", b"alerts", "device_info", b"device_info", "device_state", b"device_state", "downlink_throughput_bps", b"downlink_throughput_bps", "obstruction_stats", b"obstruction_stats", "pop_ping_drop_rate", b"pop_ping_drop_rate", "pop_ping_latency_ms", b"pop_ping_latency_ms", "seconds_to_first_nonempty_slot", b"seconds_to_first_nonempty_slot", "snr", b"snr", "state", b"state", "stow_requested", b"stow_requested", "uplink_throughput_bps", b"uplink_throughput_bps"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_alerts", b"_alerts", "_device_info", b"_device_info", "_device_state", b"_device_state", "_downlink_throughput_bps", b"_downlink_throughput_bps", "_obstruction_stats", b"_obstruction_stats", "_pop_ping_drop_rate", b"_pop_ping_drop_rate", "_pop_ping_latency_ms", b"_pop_ping_latency_ms", "_seconds_to_first_nonempty_slot", b"_seconds_to_first_nonempty_slot", "_snr", b"_snr", "_state", b"_state", "_stow_requested", b"_stow_requested", "_uplink_throughput_bps", b"_uplink_throughput_bps", "alerts", b"alerts", "device_info", b"device_info", "device_state", b"device_state", "downlink_throughput_bps", b"downlink_throughput_bps", "obstruction_stats", b"obstruction_stats", "pop_ping_drop_rate", b"pop_ping_drop_rate", "pop_ping_latency_ms", b"pop_ping_latency_ms", "seconds_to_first_nonempty_slot", b"seconds_to_first_nonempty_slot", "snr", b"snr", "state", b"state", "stow_requested", b"stow_requested", "uplink_throughput_bps", b"uplink_throughput_bps"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_alerts", b"_alerts"]) -> typing.Literal["alerts"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_device_info", b"_device_info"]) -> typing.Literal["device_info"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_device_state", b"_device_state"]) -> typing.Literal["device_state"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_downlink_throughput_bps", b"_downlink_throughput_bps"]) -> typing.Literal["downlink_throughput_bps"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_obstruction_stats", b"_obstruction_stats"]) -> typing.Literal["obstruction_stats"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pop_ping_drop_rate", b"_pop_ping_drop_rate"]) -> typing.Literal["pop_ping_drop_rate"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pop_ping_latency_ms", b"_pop_ping_latency_ms"]) -> typing.Literal["pop_ping_latency_ms"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_to_first_nonempty_slot", b"_seconds_to_first_nonempty_slot"]) -> typing.Literal["seconds_to_first_nonempty_slot"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_snr", b"_snr"]) -> typing.Literal["snr"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_state", b"_state"]) -> typing.Literal["state"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_stow_requested", b"_stow_requested"]) -> typing.Literal["stow_requested"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_uplink_throughput_bps", b"_uplink_throughput_bps"]) -> typing.Literal["uplink_throughput_bps"] | None: ...

global___DishGetStatusResponse = DishGetStatusResponse

@typing.final
class DishGetObstructionMapRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DishGetObstructionMapRequest = DishGetObstructionMapRequest

@typing.final
class DishGetObstructionMapResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_ROWS_FIELD_NUMBER: builtins.int
    NUM_COLS_FIELD_NUMBER: builtins.int
    SNR_FIELD_NUMBER: builtins.int
    num_rows: builtins.int
    num_cols: builtins.int
    @property
    def snr(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        num_rows: builtins.int | None = ...,
        num_cols: builtins.int | None = ...,
        snr: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_num_cols", b"_num_cols", "_num_rows", b"_num_rows", "num_cols", b"num_cols", "num_rows", b"num_rows"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_num_cols", b"_num_cols", "_num_rows", b"_num_rows", "num_cols", b"num_cols", "num_rows", b"num_rows", "snr", b"snr"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_num_cols", b"_num_cols"]) -> typing.Literal["num_cols"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_num_rows", b"_num_rows"]) -> typing.Literal["num_rows"] | None: ...

global___DishGetObstructionMapResponse = DishGetObstructionMapResponse

@typing.final
class DishAlerts(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOTORS_STUCK_FIELD_NUMBER: builtins.int
    THERMAL_THROTTLE_FIELD_NUMBER: builtins.int
    THERMAL_SHUTDOWN_FIELD_NUMBER: builtins.int
    MAST_NOT_NEAR_VERTICAL_FIELD_NUMBER: builtins.int
    UNEXPECTED_LOCATION_FIELD_NUMBER: builtins.int
    SLOW_ETHERNET_SPEEDS_FIELD_NUMBER: builtins.int
    motors_stuck: builtins.bool
    thermal_throttle: builtins.bool
    thermal_shutdown: builtins.bool
    mast_not_near_vertical: builtins.bool
    unexpected_location: builtins.bool
    slow_ethernet_speeds: builtins.bool
    def __init__(
        self,
        *,
        motors_stuck: builtins.bool | None = ...,
        thermal_throttle: builtins.bool | None = ...,
        thermal_shutdown: builtins.bool | None = ...,
        mast_not_near_vertical: builtins.bool | None = ...,
        unexpected_location: builtins.bool | None = ...,
        slow_ethernet_speeds: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_mast_not_near_vertical", b"_mast_not_near_vertical", "_motors_stuck", b"_motors_stuck", "_slow_ethernet_speeds", b"_slow_ethernet_speeds", "_thermal_shutdown", b"_thermal_shutdown", "_thermal_throttle", b"_thermal_throttle", "_unexpected_location", b"_unexpected_location", "mast_not_near_vertical", b"mast_not_near_vertical", "motors_stuck", b"motors_stuck", "slow_ethernet_speeds", b"slow_ethernet_speeds", "thermal_shutdown", b"thermal_shutdown", "thermal_throttle", b"thermal_throttle", "unexpected_location", b"unexpected_location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_mast_not_near_vertical", b"_mast_not_near_vertical", "_motors_stuck", b"_motors_stuck", "_slow_ethernet_speeds", b"_slow_ethernet_speeds", "_thermal_shutdown", b"_thermal_shutdown", "_thermal_throttle", b"_thermal_throttle", "_unexpected_location", b"_unexpected_location", "mast_not_near_vertical", b"mast_not_near_vertical", "motors_stuck", b"motors_stuck", "slow_ethernet_speeds", b"slow_ethernet_speeds", "thermal_shutdown", b"thermal_shutdown", "thermal_throttle", b"thermal_throttle", "unexpected_location", b"unexpected_location"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_mast_not_near_vertical", b"_mast_not_near_vertical"]) -> typing.Literal["mast_not_near_vertical"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_motors_stuck", b"_motors_stuck"]) -> typing.Literal["motors_stuck"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_slow_ethernet_speeds", b"_slow_ethernet_speeds"]) -> typing.Literal["slow_ethernet_speeds"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_thermal_shutdown", b"_thermal_shutdown"]) -> typing.Literal["thermal_shutdown"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_thermal_throttle", b"_thermal_throttle"]) -> typing.Literal["thermal_throttle"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_unexpected_location", b"_unexpected_location"]) -> typing.Literal["unexpected_location"] | None: ...

global___DishAlerts = DishAlerts

@typing.final
class DishObstructionStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENTLY_OBSTRUCTED_FIELD_NUMBER: builtins.int
    FRACTION_OBSTRUCTED_FIELD_NUMBER: builtins.int
    LAST_24H_OBSTRUCTED_S_FIELD_NUMBER: builtins.int
    VALID_S_FIELD_NUMBER: builtins.int
    WEDGE_FRACTION_OBSTRUCTED_FIELD_NUMBER: builtins.int
    WEDGE_ABS_FRACTION_OBSTRUCTED_FIELD_NUMBER: builtins.int
    currently_obstructed: builtins.bool
    fraction_obstructed: builtins.float
    last_24h_obstructed_s: builtins.float
    valid_s: builtins.float
    @property
    def wedge_fraction_obstructed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def wedge_abs_fraction_obstructed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        currently_obstructed: builtins.bool | None = ...,
        fraction_obstructed: builtins.float | None = ...,
        last_24h_obstructed_s: builtins.float | None = ...,
        valid_s: builtins.float | None = ...,
        wedge_fraction_obstructed: collections.abc.Iterable[builtins.float] | None = ...,
        wedge_abs_fraction_obstructed: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_currently_obstructed", b"_currently_obstructed", "_fraction_obstructed", b"_fraction_obstructed", "_last_24h_obstructed_s", b"_last_24h_obstructed_s", "_valid_s", b"_valid_s", "currently_obstructed", b"currently_obstructed", "fraction_obstructed", b"fraction_obstructed", "last_24h_obstructed_s", b"last_24h_obstructed_s", "valid_s", b"valid_s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_currently_obstructed", b"_currently_obstructed", "_fraction_obstructed", b"_fraction_obstructed", "_last_24h_obstructed_s", b"_last_24h_obstructed_s", "_valid_s", b"_valid_s", "currently_obstructed", b"currently_obstructed", "fraction_obstructed", b"fraction_obstructed", "last_24h_obstructed_s", b"last_24h_obstructed_s", "valid_s", b"valid_s", "wedge_abs_fraction_obstructed", b"wedge_abs_fraction_obstructed", "wedge_fraction_obstructed", b"wedge_fraction_obstructed"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_currently_obstructed", b"_currently_obstructed"]) -> typing.Literal["currently_obstructed"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fraction_obstructed", b"_fraction_obstructed"]) -> typing.Literal["fraction_obstructed"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_24h_obstructed_s", b"_last_24h_obstructed_s"]) -> typing.Literal["last_24h_obstructed_s"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_valid_s", b"_valid_s"]) -> typing.Literal["valid_s"] | None: ...

global___DishObstructionStats = DishObstructionStats

@typing.final
class DishAuthenticateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISH_FIELD_NUMBER: builtins.int
    @property
    def dish(self) -> spacex.api.device.common_pb2.ChallengeResponse: ...
    def __init__(
        self,
        *,
        dish: spacex.api.device.common_pb2.ChallengeResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dish", b"_dish", "dish", b"dish"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dish", b"_dish", "dish", b"dish"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_dish", b"_dish"]) -> typing.Literal["dish"] | None: ...

global___DishAuthenticateResponse = DishAuthenticateResponse
