# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex/api/device/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spacex/api/device/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spacex.api.device import device_pb2 as spacex_dot_api_dot_device_dot_device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fspacex/api/device/service.proto\x12\x11SpaceX.API.Device\x1a\x1espacex/api/device/device.proto2\x99\x01\n\x06\x44\x65vice\x12\x43\n\x06Handle\x12\x1a.SpaceX.API.Device.Request\x1a\x1b.SpaceX.API.Device.Response\"\x00\x12J\n\x06Stream\x12\x1b.SpaceX.API.Device.ToDevice\x1a\x1d.SpaceX.API.Device.FromDevice\"\x00(\x01\x30\x01\x42\x17Z\x15spacex.com/api/deviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex.api.device.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025spacex.com/api/device'
  _globals['_DEVICE']._serialized_start=87
  _globals['_DEVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
