"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import spacex.api.device.device_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class DeviceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Handle: grpc.UnaryUnaryMultiCallable[
        spacex.api.device.device_pb2.Request,
        spacex.api.device.device_pb2.Response,
    ]

    Stream: grpc.StreamStreamMultiCallable[
        spacex.api.device.device_pb2.ToDevice,
        spacex.api.device.device_pb2.FromDevice,
    ]

class DeviceAsyncStub:
    Handle: grpc.aio.UnaryUnaryMultiCallable[
        spacex.api.device.device_pb2.Request,
        spacex.api.device.device_pb2.Response,
    ]

    Stream: grpc.aio.StreamStreamMultiCallable[
        spacex.api.device.device_pb2.ToDevice,
        spacex.api.device.device_pb2.FromDevice,
    ]

class DeviceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Handle(
        self,
        request: spacex.api.device.device_pb2.Request,
        context: _ServicerContext,
    ) -> typing.Union[spacex.api.device.device_pb2.Response, collections.abc.Awaitable[spacex.api.device.device_pb2.Response]]: ...

    @abc.abstractmethod
    def Stream(
        self,
        request_iterator: _MaybeAsyncIterator[spacex.api.device.device_pb2.ToDevice],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[spacex.api.device.device_pb2.FromDevice], collections.abc.AsyncIterator[spacex.api.device.device_pb2.FromDevice]]: ...

def add_DeviceServicer_to_server(servicer: DeviceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
