"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import spacex.api.device.common_pb2
import spacex.api.device.wifi_config_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WifiSetConfigRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIFI_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def wifi_config(self) -> spacex.api.device.wifi_config_pb2.WifiConfig: ...
    def __init__(
        self,
        *,
        wifi_config: spacex.api.device.wifi_config_pb2.WifiConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_wifi_config", b"_wifi_config", "wifi_config", b"wifi_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_wifi_config", b"_wifi_config", "wifi_config", b"wifi_config"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_wifi_config", b"_wifi_config"]) -> typing.Literal["wifi_config"] | None: ...

global___WifiSetConfigRequest = WifiSetConfigRequest

@typing.final
class WifiSetConfigResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATED_WIFI_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def updated_wifi_config(self) -> spacex.api.device.wifi_config_pb2.WifiConfig: ...
    def __init__(
        self,
        *,
        updated_wifi_config: spacex.api.device.wifi_config_pb2.WifiConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_updated_wifi_config", b"_updated_wifi_config", "updated_wifi_config", b"updated_wifi_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_updated_wifi_config", b"_updated_wifi_config", "updated_wifi_config", b"updated_wifi_config"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_updated_wifi_config", b"_updated_wifi_config"]) -> typing.Literal["updated_wifi_config"] | None: ...

global___WifiSetConfigResponse = WifiSetConfigResponse

@typing.final
class WifiGetConfigRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WifiGetConfigRequest = WifiGetConfigRequest

@typing.final
class WifiGetConfigResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIFI_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def wifi_config(self) -> spacex.api.device.wifi_config_pb2.WifiConfig: ...
    def __init__(
        self,
        *,
        wifi_config: spacex.api.device.wifi_config_pb2.WifiConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_wifi_config", b"_wifi_config", "wifi_config", b"wifi_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_wifi_config", b"_wifi_config", "wifi_config", b"wifi_config"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_wifi_config", b"_wifi_config"]) -> typing.Literal["wifi_config"] | None: ...

global___WifiGetConfigResponse = WifiGetConfigResponse

@typing.final
class WifiGetClientsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WifiGetClientsRequest = WifiGetClientsRequest

@typing.final
class WifiGetClientsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENTS_FIELD_NUMBER: builtins.int
    @property
    def clients(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WifiClient]: ...
    def __init__(
        self,
        *,
        clients: collections.abc.Iterable[global___WifiClient] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clients", b"clients"]) -> None: ...

global___WifiGetClientsResponse = WifiGetClientsResponse

@typing.final
class WifiGetHistoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENT_FIELD_NUMBER: builtins.int
    PING_DROP_RATE_FIELD_NUMBER: builtins.int
    PING_LATENCY_MS_FIELD_NUMBER: builtins.int
    current: builtins.int
    @property
    def ping_drop_rate(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def ping_latency_ms(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        current: builtins.int | None = ...,
        ping_drop_rate: collections.abc.Iterable[builtins.float] | None = ...,
        ping_latency_ms: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_current", b"_current", "current", b"current"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_current", b"_current", "current", b"current", "ping_drop_rate", b"ping_drop_rate", "ping_latency_ms", b"ping_latency_ms"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_current", b"_current"]) -> typing.Literal["current"] | None: ...

global___WifiGetHistoryResponse = WifiGetHistoryResponse

@typing.final
class WifiNewClientConnectedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_FIELD_NUMBER: builtins.int
    @property
    def client(self) -> global___WifiClient: ...
    def __init__(
        self,
        *,
        client: global___WifiClient | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_client", b"_client", "client", b"client"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_client", b"_client", "client", b"client"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_client", b"_client"]) -> typing.Literal["client"] | None: ...

global___WifiNewClientConnectedEvent = WifiNewClientConnectedEvent

@typing.final
class WifiClient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Interface:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _InterfaceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WifiClient._Interface.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: WifiClient._Interface.ValueType  # 0
        ETH: WifiClient._Interface.ValueType  # 1
        RF_2GHZ: WifiClient._Interface.ValueType  # 2
        RF_5GHZ: WifiClient._Interface.ValueType  # 3

    class Interface(_Interface, metaclass=_InterfaceEnumTypeWrapper): ...
    UNKNOWN: WifiClient.Interface.ValueType  # 0
    ETH: WifiClient.Interface.ValueType  # 1
    RF_2GHZ: WifiClient.Interface.ValueType  # 2
    RF_5GHZ: WifiClient.Interface.ValueType  # 3

    @typing.final
    class RxStats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BYTES_FIELD_NUMBER: builtins.int
        COUNT_ERRORS_FIELD_NUMBER: builtins.int
        NSS_FIELD_NUMBER: builtins.int
        bytes: builtins.int
        count_errors: builtins.int
        nss: builtins.int
        def __init__(
            self,
            *,
            bytes: builtins.int | None = ...,
            count_errors: builtins.int | None = ...,
            nss: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_bytes", b"_bytes", "_count_errors", b"_count_errors", "_nss", b"_nss", "bytes", b"bytes", "count_errors", b"count_errors", "nss", b"nss"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_bytes", b"_bytes", "_count_errors", b"_count_errors", "_nss", b"_nss", "bytes", b"bytes", "count_errors", b"count_errors", "nss", b"nss"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_bytes", b"_bytes"]) -> typing.Literal["bytes"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_count_errors", b"_count_errors"]) -> typing.Literal["count_errors"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_nss", b"_nss"]) -> typing.Literal["nss"] | None: ...

    @typing.final
    class TxStats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BYTES_FIELD_NUMBER: builtins.int
        SUCCESS_BYTES_FIELD_NUMBER: builtins.int
        NSS_FIELD_NUMBER: builtins.int
        bytes: builtins.int
        success_bytes: builtins.int
        nss: builtins.int
        def __init__(
            self,
            *,
            bytes: builtins.int | None = ...,
            success_bytes: builtins.int | None = ...,
            nss: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_bytes", b"_bytes", "_nss", b"_nss", "_success_bytes", b"_success_bytes", "bytes", b"bytes", "nss", b"nss", "success_bytes", b"success_bytes"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_bytes", b"_bytes", "_nss", b"_nss", "_success_bytes", b"_success_bytes", "bytes", b"bytes", "nss", b"nss", "success_bytes", b"success_bytes"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_bytes", b"_bytes"]) -> typing.Literal["bytes"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_nss", b"_nss"]) -> typing.Literal["nss"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_success_bytes", b"_success_bytes"]) -> typing.Literal["success_bytes"] | None: ...

    NAME_FIELD_NUMBER: builtins.int
    MAC_ADDRESS_FIELD_NUMBER: builtins.int
    IP_ADDRESS_FIELD_NUMBER: builtins.int
    SIGNAL_STRENGTH_FIELD_NUMBER: builtins.int
    RX_STATS_FIELD_NUMBER: builtins.int
    TX_STATS_FIELD_NUMBER: builtins.int
    ASSOCIATED_TIME_S_FIELD_NUMBER: builtins.int
    MODE_STR_FIELD_NUMBER: builtins.int
    IFACE_FIELD_NUMBER: builtins.int
    SNR_FIELD_NUMBER: builtins.int
    PSMODE_FIELD_NUMBER: builtins.int
    name: builtins.str
    mac_address: builtins.str
    ip_address: builtins.str
    signal_strength: builtins.float
    associated_time_s: builtins.int
    mode_str: builtins.str
    iface: global___WifiClient.Interface.ValueType
    snr: builtins.float
    psmode: builtins.int
    @property
    def rx_stats(self) -> global___WifiClient.RxStats: ...
    @property
    def tx_stats(self) -> global___WifiClient.TxStats: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        mac_address: builtins.str | None = ...,
        ip_address: builtins.str | None = ...,
        signal_strength: builtins.float | None = ...,
        rx_stats: global___WifiClient.RxStats | None = ...,
        tx_stats: global___WifiClient.TxStats | None = ...,
        associated_time_s: builtins.int | None = ...,
        mode_str: builtins.str | None = ...,
        iface: global___WifiClient.Interface.ValueType | None = ...,
        snr: builtins.float | None = ...,
        psmode: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_associated_time_s", b"_associated_time_s", "_iface", b"_iface", "_ip_address", b"_ip_address", "_mac_address", b"_mac_address", "_mode_str", b"_mode_str", "_name", b"_name", "_psmode", b"_psmode", "_rx_stats", b"_rx_stats", "_signal_strength", b"_signal_strength", "_snr", b"_snr", "_tx_stats", b"_tx_stats", "associated_time_s", b"associated_time_s", "iface", b"iface", "ip_address", b"ip_address", "mac_address", b"mac_address", "mode_str", b"mode_str", "name", b"name", "psmode", b"psmode", "rx_stats", b"rx_stats", "signal_strength", b"signal_strength", "snr", b"snr", "tx_stats", b"tx_stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_associated_time_s", b"_associated_time_s", "_iface", b"_iface", "_ip_address", b"_ip_address", "_mac_address", b"_mac_address", "_mode_str", b"_mode_str", "_name", b"_name", "_psmode", b"_psmode", "_rx_stats", b"_rx_stats", "_signal_strength", b"_signal_strength", "_snr", b"_snr", "_tx_stats", b"_tx_stats", "associated_time_s", b"associated_time_s", "iface", b"iface", "ip_address", b"ip_address", "mac_address", b"mac_address", "mode_str", b"mode_str", "name", b"name", "psmode", b"psmode", "rx_stats", b"rx_stats", "signal_strength", b"signal_strength", "snr", b"snr", "tx_stats", b"tx_stats"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_associated_time_s", b"_associated_time_s"]) -> typing.Literal["associated_time_s"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_iface", b"_iface"]) -> typing.Literal["iface"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_ip_address", b"_ip_address"]) -> typing.Literal["ip_address"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_mac_address", b"_mac_address"]) -> typing.Literal["mac_address"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_mode_str", b"_mode_str"]) -> typing.Literal["mode_str"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_psmode", b"_psmode"]) -> typing.Literal["psmode"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rx_stats", b"_rx_stats"]) -> typing.Literal["rx_stats"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_signal_strength", b"_signal_strength"]) -> typing.Literal["signal_strength"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_snr", b"_snr"]) -> typing.Literal["snr"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tx_stats", b"_tx_stats"]) -> typing.Literal["tx_stats"] | None: ...

global___WifiClient = WifiClient

@typing.final
class WifiSetupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SKIP_FIELD_NUMBER: builtins.int
    NETWORK_NAME_FIELD_NUMBER: builtins.int
    NETWORK_PASSWORD_FIELD_NUMBER: builtins.int
    skip: builtins.bool
    network_name: builtins.str
    network_password: builtins.str
    def __init__(
        self,
        *,
        skip: builtins.bool | None = ...,
        network_name: builtins.str | None = ...,
        network_password: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_network_name", b"_network_name", "_network_password", b"_network_password", "_skip", b"_skip", "network_name", b"network_name", "network_password", b"network_password", "skip", b"skip"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_network_name", b"_network_name", "_network_password", b"_network_password", "_skip", b"_skip", "network_name", b"network_name", "network_password", b"network_password", "skip", b"skip"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_network_name", b"_network_name"]) -> typing.Literal["network_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_network_password", b"_network_password"]) -> typing.Literal["network_password"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_skip", b"_skip"]) -> typing.Literal["skip"] | None: ...

global___WifiSetupRequest = WifiSetupRequest

@typing.final
class WifiSetupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WifiSetupResponse = WifiSetupResponse

@typing.final
class WifiGetStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEVICE_INFO_FIELD_NUMBER: builtins.int
    DEVICE_STATE_FIELD_NUMBER: builtins.int
    CAPTIVE_PORTAL_ENABLED_FIELD_NUMBER: builtins.int
    CLIENTS_FIELD_NUMBER: builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: builtins.int
    SKU_FIELD_NUMBER: builtins.int
    IPV4_WAN_ADDRESS_FIELD_NUMBER: builtins.int
    PING_DROP_RATE_FIELD_NUMBER: builtins.int
    PING_LATENCY_MS_FIELD_NUMBER: builtins.int
    captive_portal_enabled: builtins.bool
    serial_number: builtins.str
    sku: builtins.str
    ipv4_wan_address: builtins.str
    ping_drop_rate: builtins.float
    ping_latency_ms: builtins.float
    @property
    def device_info(self) -> spacex.api.device.common_pb2.DeviceInfo: ...
    @property
    def device_state(self) -> spacex.api.device.common_pb2.DeviceState: ...
    @property
    def clients(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WifiClient]: ...
    def __init__(
        self,
        *,
        device_info: spacex.api.device.common_pb2.DeviceInfo | None = ...,
        device_state: spacex.api.device.common_pb2.DeviceState | None = ...,
        captive_portal_enabled: builtins.bool | None = ...,
        clients: collections.abc.Iterable[global___WifiClient] | None = ...,
        serial_number: builtins.str | None = ...,
        sku: builtins.str | None = ...,
        ipv4_wan_address: builtins.str | None = ...,
        ping_drop_rate: builtins.float | None = ...,
        ping_latency_ms: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_captive_portal_enabled", b"_captive_portal_enabled", "_device_info", b"_device_info", "_device_state", b"_device_state", "_ipv4_wan_address", b"_ipv4_wan_address", "_ping_drop_rate", b"_ping_drop_rate", "_ping_latency_ms", b"_ping_latency_ms", "_serial_number", b"_serial_number", "_sku", b"_sku", "captive_portal_enabled", b"captive_portal_enabled", "device_info", b"device_info", "device_state", b"device_state", "ipv4_wan_address", b"ipv4_wan_address", "ping_drop_rate", b"ping_drop_rate", "ping_latency_ms", b"ping_latency_ms", "serial_number", b"serial_number", "sku", b"sku"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_captive_portal_enabled", b"_captive_portal_enabled", "_device_info", b"_device_info", "_device_state", b"_device_state", "_ipv4_wan_address", b"_ipv4_wan_address", "_ping_drop_rate", b"_ping_drop_rate", "_ping_latency_ms", b"_ping_latency_ms", "_serial_number", b"_serial_number", "_sku", b"_sku", "captive_portal_enabled", b"captive_portal_enabled", "clients", b"clients", "device_info", b"device_info", "device_state", b"device_state", "ipv4_wan_address", b"ipv4_wan_address", "ping_drop_rate", b"ping_drop_rate", "ping_latency_ms", b"ping_latency_ms", "serial_number", b"serial_number", "sku", b"sku"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_captive_portal_enabled", b"_captive_portal_enabled"]) -> typing.Literal["captive_portal_enabled"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_device_info", b"_device_info"]) -> typing.Literal["device_info"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_device_state", b"_device_state"]) -> typing.Literal["device_state"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_ipv4_wan_address", b"_ipv4_wan_address"]) -> typing.Literal["ipv4_wan_address"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_ping_drop_rate", b"_ping_drop_rate"]) -> typing.Literal["ping_drop_rate"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_ping_latency_ms", b"_ping_latency_ms"]) -> typing.Literal["ping_latency_ms"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_serial_number", b"_serial_number"]) -> typing.Literal["serial_number"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sku", b"_sku"]) -> typing.Literal["sku"] | None: ...

global___WifiGetStatusResponse = WifiGetStatusResponse

@typing.final
class WifiAuthenticateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHALLENGE_FIELD_NUMBER: builtins.int
    @property
    def challenge(self) -> spacex.api.device.common_pb2.SignedData: ...
    def __init__(
        self,
        *,
        challenge: spacex.api.device.common_pb2.SignedData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_challenge", b"_challenge", "challenge", b"challenge"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_challenge", b"_challenge", "challenge", b"challenge"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_challenge", b"_challenge"]) -> typing.Literal["challenge"] | None: ...

global___WifiAuthenticateRequest = WifiAuthenticateRequest

@typing.final
class WifiAuthenticateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIFI_FIELD_NUMBER: builtins.int
    DISH_FIELD_NUMBER: builtins.int
    @property
    def wifi(self) -> spacex.api.device.common_pb2.ChallengeResponse: ...
    @property
    def dish(self) -> spacex.api.device.common_pb2.ChallengeResponse: ...
    def __init__(
        self,
        *,
        wifi: spacex.api.device.common_pb2.ChallengeResponse | None = ...,
        dish: spacex.api.device.common_pb2.ChallengeResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dish", b"_dish", "_wifi", b"_wifi", "dish", b"dish", "wifi", b"wifi"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dish", b"_dish", "_wifi", b"_wifi", "dish", b"dish", "wifi", b"wifi"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dish", b"_dish"]) -> typing.Literal["dish"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_wifi", b"_wifi"]) -> typing.Literal["wifi"] | None: ...

global___WifiAuthenticateResponse = WifiAuthenticateResponse

@typing.final
class WifiAccountBondingEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISH_ID_FIELD_NUMBER: builtins.int
    dish_id: builtins.str
    def __init__(
        self,
        *,
        dish_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dish_id", b"_dish_id", "dish_id", b"dish_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dish_id", b"_dish_id", "dish_id", b"dish_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_dish_id", b"_dish_id"]) -> typing.Literal["dish_id"] | None: ...

global___WifiAccountBondingEvent = WifiAccountBondingEvent

@typing.final
class PingMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LATENCY_MEAN_MS_FIELD_NUMBER: builtins.int
    LATENCY_STDDEV_MS_FIELD_NUMBER: builtins.int
    LATENCY_MEAN_MS_5M_FIELD_NUMBER: builtins.int
    LATENCY_MEAN_MS_1H_FIELD_NUMBER: builtins.int
    LATENCY_MEAN_MS_1D_FIELD_NUMBER: builtins.int
    DROP_RATE_FIELD_NUMBER: builtins.int
    DROP_RATE_5M_FIELD_NUMBER: builtins.int
    DROP_RATE_1H_FIELD_NUMBER: builtins.int
    DROP_RATE_1D_FIELD_NUMBER: builtins.int
    SECONDS_SINCE_LAST_SUCCESS_FIELD_NUMBER: builtins.int
    SECONDS_SINCE_LAST_1S_OUTAGE_FIELD_NUMBER: builtins.int
    SECONDS_SINCE_LAST_2S_OUTAGE_FIELD_NUMBER: builtins.int
    SECONDS_SINCE_LAST_5S_OUTAGE_FIELD_NUMBER: builtins.int
    SECONDS_SINCE_LAST_15S_OUTAGE_FIELD_NUMBER: builtins.int
    SECONDS_SINCE_LAST_60S_OUTAGE_FIELD_NUMBER: builtins.int
    SECONDS_SINCE_LAST_300S_OUTAGE_FIELD_NUMBER: builtins.int
    HAPPY_HOURS_1S_1D_FIELD_NUMBER: builtins.int
    HAPPY_HOURS_2S_1D_FIELD_NUMBER: builtins.int
    HAPPY_HOURS_5S_1D_FIELD_NUMBER: builtins.int
    latency_mean_ms: builtins.float
    latency_stddev_ms: builtins.float
    latency_mean_ms_5m: builtins.float
    latency_mean_ms_1h: builtins.float
    latency_mean_ms_1d: builtins.float
    drop_rate: builtins.float
    drop_rate_5m: builtins.float
    drop_rate_1h: builtins.float
    drop_rate_1d: builtins.float
    seconds_since_last_success: builtins.float
    seconds_since_last_1s_outage: builtins.float
    seconds_since_last_2s_outage: builtins.float
    seconds_since_last_5s_outage: builtins.float
    seconds_since_last_15s_outage: builtins.float
    seconds_since_last_60s_outage: builtins.float
    seconds_since_last_300s_outage: builtins.float
    happy_hours_1s_1d: builtins.float
    happy_hours_2s_1d: builtins.float
    happy_hours_5s_1d: builtins.float
    def __init__(
        self,
        *,
        latency_mean_ms: builtins.float | None = ...,
        latency_stddev_ms: builtins.float | None = ...,
        latency_mean_ms_5m: builtins.float | None = ...,
        latency_mean_ms_1h: builtins.float | None = ...,
        latency_mean_ms_1d: builtins.float | None = ...,
        drop_rate: builtins.float | None = ...,
        drop_rate_5m: builtins.float | None = ...,
        drop_rate_1h: builtins.float | None = ...,
        drop_rate_1d: builtins.float | None = ...,
        seconds_since_last_success: builtins.float | None = ...,
        seconds_since_last_1s_outage: builtins.float | None = ...,
        seconds_since_last_2s_outage: builtins.float | None = ...,
        seconds_since_last_5s_outage: builtins.float | None = ...,
        seconds_since_last_15s_outage: builtins.float | None = ...,
        seconds_since_last_60s_outage: builtins.float | None = ...,
        seconds_since_last_300s_outage: builtins.float | None = ...,
        happy_hours_1s_1d: builtins.float | None = ...,
        happy_hours_2s_1d: builtins.float | None = ...,
        happy_hours_5s_1d: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_drop_rate", b"_drop_rate", "_drop_rate_1d", b"_drop_rate_1d", "_drop_rate_1h", b"_drop_rate_1h", "_drop_rate_5m", b"_drop_rate_5m", "_happy_hours_1s_1d", b"_happy_hours_1s_1d", "_happy_hours_2s_1d", b"_happy_hours_2s_1d", "_happy_hours_5s_1d", b"_happy_hours_5s_1d", "_latency_mean_ms", b"_latency_mean_ms", "_latency_mean_ms_1d", b"_latency_mean_ms_1d", "_latency_mean_ms_1h", b"_latency_mean_ms_1h", "_latency_mean_ms_5m", b"_latency_mean_ms_5m", "_latency_stddev_ms", b"_latency_stddev_ms", "_seconds_since_last_15s_outage", b"_seconds_since_last_15s_outage", "_seconds_since_last_1s_outage", b"_seconds_since_last_1s_outage", "_seconds_since_last_2s_outage", b"_seconds_since_last_2s_outage", "_seconds_since_last_300s_outage", b"_seconds_since_last_300s_outage", "_seconds_since_last_5s_outage", b"_seconds_since_last_5s_outage", "_seconds_since_last_60s_outage", b"_seconds_since_last_60s_outage", "_seconds_since_last_success", b"_seconds_since_last_success", "drop_rate", b"drop_rate", "drop_rate_1d", b"drop_rate_1d", "drop_rate_1h", b"drop_rate_1h", "drop_rate_5m", b"drop_rate_5m", "happy_hours_1s_1d", b"happy_hours_1s_1d", "happy_hours_2s_1d", b"happy_hours_2s_1d", "happy_hours_5s_1d", b"happy_hours_5s_1d", "latency_mean_ms", b"latency_mean_ms", "latency_mean_ms_1d", b"latency_mean_ms_1d", "latency_mean_ms_1h", b"latency_mean_ms_1h", "latency_mean_ms_5m", b"latency_mean_ms_5m", "latency_stddev_ms", b"latency_stddev_ms", "seconds_since_last_15s_outage", b"seconds_since_last_15s_outage", "seconds_since_last_1s_outage", b"seconds_since_last_1s_outage", "seconds_since_last_2s_outage", b"seconds_since_last_2s_outage", "seconds_since_last_300s_outage", b"seconds_since_last_300s_outage", "seconds_since_last_5s_outage", b"seconds_since_last_5s_outage", "seconds_since_last_60s_outage", b"seconds_since_last_60s_outage", "seconds_since_last_success", b"seconds_since_last_success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_drop_rate", b"_drop_rate", "_drop_rate_1d", b"_drop_rate_1d", "_drop_rate_1h", b"_drop_rate_1h", "_drop_rate_5m", b"_drop_rate_5m", "_happy_hours_1s_1d", b"_happy_hours_1s_1d", "_happy_hours_2s_1d", b"_happy_hours_2s_1d", "_happy_hours_5s_1d", b"_happy_hours_5s_1d", "_latency_mean_ms", b"_latency_mean_ms", "_latency_mean_ms_1d", b"_latency_mean_ms_1d", "_latency_mean_ms_1h", b"_latency_mean_ms_1h", "_latency_mean_ms_5m", b"_latency_mean_ms_5m", "_latency_stddev_ms", b"_latency_stddev_ms", "_seconds_since_last_15s_outage", b"_seconds_since_last_15s_outage", "_seconds_since_last_1s_outage", b"_seconds_since_last_1s_outage", "_seconds_since_last_2s_outage", b"_seconds_since_last_2s_outage", "_seconds_since_last_300s_outage", b"_seconds_since_last_300s_outage", "_seconds_since_last_5s_outage", b"_seconds_since_last_5s_outage", "_seconds_since_last_60s_outage", b"_seconds_since_last_60s_outage", "_seconds_since_last_success", b"_seconds_since_last_success", "drop_rate", b"drop_rate", "drop_rate_1d", b"drop_rate_1d", "drop_rate_1h", b"drop_rate_1h", "drop_rate_5m", b"drop_rate_5m", "happy_hours_1s_1d", b"happy_hours_1s_1d", "happy_hours_2s_1d", b"happy_hours_2s_1d", "happy_hours_5s_1d", b"happy_hours_5s_1d", "latency_mean_ms", b"latency_mean_ms", "latency_mean_ms_1d", b"latency_mean_ms_1d", "latency_mean_ms_1h", b"latency_mean_ms_1h", "latency_mean_ms_5m", b"latency_mean_ms_5m", "latency_stddev_ms", b"latency_stddev_ms", "seconds_since_last_15s_outage", b"seconds_since_last_15s_outage", "seconds_since_last_1s_outage", b"seconds_since_last_1s_outage", "seconds_since_last_2s_outage", b"seconds_since_last_2s_outage", "seconds_since_last_300s_outage", b"seconds_since_last_300s_outage", "seconds_since_last_5s_outage", b"seconds_since_last_5s_outage", "seconds_since_last_60s_outage", b"seconds_since_last_60s_outage", "seconds_since_last_success", b"seconds_since_last_success"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_drop_rate", b"_drop_rate"]) -> typing.Literal["drop_rate"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_drop_rate_1d", b"_drop_rate_1d"]) -> typing.Literal["drop_rate_1d"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_drop_rate_1h", b"_drop_rate_1h"]) -> typing.Literal["drop_rate_1h"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_drop_rate_5m", b"_drop_rate_5m"]) -> typing.Literal["drop_rate_5m"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_happy_hours_1s_1d", b"_happy_hours_1s_1d"]) -> typing.Literal["happy_hours_1s_1d"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_happy_hours_2s_1d", b"_happy_hours_2s_1d"]) -> typing.Literal["happy_hours_2s_1d"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_happy_hours_5s_1d", b"_happy_hours_5s_1d"]) -> typing.Literal["happy_hours_5s_1d"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latency_mean_ms", b"_latency_mean_ms"]) -> typing.Literal["latency_mean_ms"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latency_mean_ms_1d", b"_latency_mean_ms_1d"]) -> typing.Literal["latency_mean_ms_1d"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latency_mean_ms_1h", b"_latency_mean_ms_1h"]) -> typing.Literal["latency_mean_ms_1h"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latency_mean_ms_5m", b"_latency_mean_ms_5m"]) -> typing.Literal["latency_mean_ms_5m"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latency_stddev_ms", b"_latency_stddev_ms"]) -> typing.Literal["latency_stddev_ms"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_since_last_15s_outage", b"_seconds_since_last_15s_outage"]) -> typing.Literal["seconds_since_last_15s_outage"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_since_last_1s_outage", b"_seconds_since_last_1s_outage"]) -> typing.Literal["seconds_since_last_1s_outage"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_since_last_2s_outage", b"_seconds_since_last_2s_outage"]) -> typing.Literal["seconds_since_last_2s_outage"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_since_last_300s_outage", b"_seconds_since_last_300s_outage"]) -> typing.Literal["seconds_since_last_300s_outage"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_since_last_5s_outage", b"_seconds_since_last_5s_outage"]) -> typing.Literal["seconds_since_last_5s_outage"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_since_last_60s_outage", b"_seconds_since_last_60s_outage"]) -> typing.Literal["seconds_since_last_60s_outage"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_seconds_since_last_success", b"_seconds_since_last_success"]) -> typing.Literal["seconds_since_last_success"] | None: ...

global___PingMetrics = PingMetrics

@typing.final
class WifiGetPingMetricsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WifiGetPingMetricsRequest = WifiGetPingMetricsRequest

@typing.final
class WifiGetPingMetricsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTERNET_FIELD_NUMBER: builtins.int
    @property
    def internet(self) -> global___PingMetrics: ...
    def __init__(
        self,
        *,
        internet: global___PingMetrics | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_internet", b"_internet", "internet", b"internet"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_internet", b"_internet", "internet", b"internet"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_internet", b"_internet"]) -> typing.Literal["internet"] | None: ...

global___WifiGetPingMetricsResponse = WifiGetPingMetricsResponse

@typing.final
class WifiGetDiagnosticsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WifiGetDiagnosticsRequest = WifiGetDiagnosticsRequest

@typing.final
class WifiGetDiagnosticsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NETWORK_SCAN_FIELD_NUMBER: builtins.int
    WIFI_NETWORKS_FIELD_NUMBER: builtins.int
    @property
    def network_scan(self) -> global___WifiScanResults: ...
    @property
    def wifi_networks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WifiNetwork]: ...
    def __init__(
        self,
        *,
        network_scan: global___WifiScanResults | None = ...,
        wifi_networks: collections.abc.Iterable[global___WifiNetwork] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_network_scan", b"_network_scan", "network_scan", b"network_scan"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_network_scan", b"_network_scan", "network_scan", b"network_scan", "wifi_networks", b"wifi_networks"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_network_scan", b"_network_scan"]) -> typing.Literal["network_scan"] | None: ...

global___WifiGetDiagnosticsResponse = WifiGetDiagnosticsResponse

@typing.final
class WifiScanResults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Network(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Source:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _SourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WifiScanResults.Network._Source.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            UNKNOWN: WifiScanResults.Network._Source.ValueType  # 0
            SCAN_2_4GHZ: WifiScanResults.Network._Source.ValueType  # 1
            SCAN_5GHZ: WifiScanResults.Network._Source.ValueType  # 2

        class Source(_Source, metaclass=_SourceEnumTypeWrapper): ...
        UNKNOWN: WifiScanResults.Network.Source.ValueType  # 0
        SCAN_2_4GHZ: WifiScanResults.Network.Source.ValueType  # 1
        SCAN_5GHZ: WifiScanResults.Network.Source.ValueType  # 2

        SOURCE_FIELD_NUMBER: builtins.int
        SSID_FIELD_NUMBER: builtins.int
        BSSID_FIELD_NUMBER: builtins.int
        FREQUENCY_GHZ_FIELD_NUMBER: builtins.int
        CHANNEL_FIELD_NUMBER: builtins.int
        SIGNAL_LEVEL_DBM_FIELD_NUMBER: builtins.int
        NOISE_LEVEL_DBM_FIELD_NUMBER: builtins.int
        HAS_ENCRYPTION_KEY_FIELD_NUMBER: builtins.int
        PHY_MODE_STR_FIELD_NUMBER: builtins.int
        source: global___WifiScanResults.Network.Source.ValueType
        ssid: builtins.str
        bssid: builtins.str
        frequency_ghz: builtins.str
        channel: builtins.int
        signal_level_dbm: builtins.int
        noise_level_dbm: builtins.int
        has_encryption_key: builtins.bool
        phy_mode_str: builtins.str
        def __init__(
            self,
            *,
            source: global___WifiScanResults.Network.Source.ValueType | None = ...,
            ssid: builtins.str | None = ...,
            bssid: builtins.str | None = ...,
            frequency_ghz: builtins.str | None = ...,
            channel: builtins.int | None = ...,
            signal_level_dbm: builtins.int | None = ...,
            noise_level_dbm: builtins.int | None = ...,
            has_encryption_key: builtins.bool | None = ...,
            phy_mode_str: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_bssid", b"_bssid", "_channel", b"_channel", "_frequency_ghz", b"_frequency_ghz", "_has_encryption_key", b"_has_encryption_key", "_noise_level_dbm", b"_noise_level_dbm", "_phy_mode_str", b"_phy_mode_str", "_signal_level_dbm", b"_signal_level_dbm", "_source", b"_source", "_ssid", b"_ssid", "bssid", b"bssid", "channel", b"channel", "frequency_ghz", b"frequency_ghz", "has_encryption_key", b"has_encryption_key", "noise_level_dbm", b"noise_level_dbm", "phy_mode_str", b"phy_mode_str", "signal_level_dbm", b"signal_level_dbm", "source", b"source", "ssid", b"ssid"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_bssid", b"_bssid", "_channel", b"_channel", "_frequency_ghz", b"_frequency_ghz", "_has_encryption_key", b"_has_encryption_key", "_noise_level_dbm", b"_noise_level_dbm", "_phy_mode_str", b"_phy_mode_str", "_signal_level_dbm", b"_signal_level_dbm", "_source", b"_source", "_ssid", b"_ssid", "bssid", b"bssid", "channel", b"channel", "frequency_ghz", b"frequency_ghz", "has_encryption_key", b"has_encryption_key", "noise_level_dbm", b"noise_level_dbm", "phy_mode_str", b"phy_mode_str", "signal_level_dbm", b"signal_level_dbm", "source", b"source", "ssid", b"ssid"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_bssid", b"_bssid"]) -> typing.Literal["bssid"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_channel", b"_channel"]) -> typing.Literal["channel"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_frequency_ghz", b"_frequency_ghz"]) -> typing.Literal["frequency_ghz"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_has_encryption_key", b"_has_encryption_key"]) -> typing.Literal["has_encryption_key"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_noise_level_dbm", b"_noise_level_dbm"]) -> typing.Literal["noise_level_dbm"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_phy_mode_str", b"_phy_mode_str"]) -> typing.Literal["phy_mode_str"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_signal_level_dbm", b"_signal_level_dbm"]) -> typing.Literal["signal_level_dbm"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_source", b"_source"]) -> typing.Literal["source"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_ssid", b"_ssid"]) -> typing.Literal["ssid"] | None: ...

    NETWORKS_FIELD_NUMBER: builtins.int
    @property
    def networks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WifiScanResults.Network]: ...
    def __init__(
        self,
        *,
        networks: collections.abc.Iterable[global___WifiScanResults.Network] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["networks", b"networks"]) -> None: ...

global___WifiScanResults = WifiScanResults

@typing.final
class WifiNetwork(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Band:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BandEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WifiNetwork._Band.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        WIFI_UNKNOWN: WifiNetwork._Band.ValueType  # 0
        WIFI_2_4GHZ: WifiNetwork._Band.ValueType  # 1
        WIFI_5GHZ: WifiNetwork._Band.ValueType  # 2

    class Band(_Band, metaclass=_BandEnumTypeWrapper): ...
    WIFI_UNKNOWN: WifiNetwork.Band.ValueType  # 0
    WIFI_2_4GHZ: WifiNetwork.Band.ValueType  # 1
    WIFI_5GHZ: WifiNetwork.Band.ValueType  # 2

    BAND_FIELD_NUMBER: builtins.int
    SSID_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    ENCRYPTION_TYPE_STR_FIELD_NUMBER: builtins.int
    band: global___WifiNetwork.Band.ValueType
    ssid: builtins.str
    channel: builtins.int
    encryption_type_str: builtins.str
    def __init__(
        self,
        *,
        band: global___WifiNetwork.Band.ValueType | None = ...,
        ssid: builtins.str | None = ...,
        channel: builtins.int | None = ...,
        encryption_type_str: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_band", b"_band", "_channel", b"_channel", "_encryption_type_str", b"_encryption_type_str", "_ssid", b"_ssid", "band", b"band", "channel", b"channel", "encryption_type_str", b"encryption_type_str", "ssid", b"ssid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_band", b"_band", "_channel", b"_channel", "_encryption_type_str", b"_encryption_type_str", "_ssid", b"_ssid", "band", b"band", "channel", b"channel", "encryption_type_str", b"encryption_type_str", "ssid", b"ssid"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_band", b"_band"]) -> typing.Literal["band"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_channel", b"_channel"]) -> typing.Literal["channel"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_encryption_type_str", b"_encryption_type_str"]) -> typing.Literal["encryption_type_str"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_ssid", b"_ssid"]) -> typing.Literal["ssid"] | None: ...

global___WifiNetwork = WifiNetwork
